/* eslint-disable react-hooks/rules-of-hooks */
import React, { useEffect } from "react";

import Head from "next/head";

import MainLayout from "@/layouts/MainLayout";

import ArticleGrid from "@/components/ui/ArticleGrid";

import { useDispatch } from "react-redux";
import { useApi } from "@/hooks/useApi";

import { getAllArticle } from "@/services/article.service";

const Articles = () => {
  const dispatch = useDispatch();
  const { call } = useApi();

  useEffect(() => {
    call(getAllArticle(dispatch));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <ArticleGrid />
      </MainLayout>
    </>
  );
};

export default Articles;
