/* eslint-disable react-hooks/exhaustive-deps */
import GameItem from "@/components/game/GameItem";
import GameCategoryDetailGrid from "@/components/ui/GameCategoryDetailGrid";
import GameCategoryGrid from "@/components/ui/GameCategoryGrid";
import { useApi } from "@/hooks/useApi";
import MainLayout from "@/layouts/MainLayout";
import {
  getAllCategories,
  getAllGame,
  getCategoryById,
} from "@/services/game.service";
import { isEmpty } from "lodash";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

const CategoryDetail = () => {
  const dispatch = useDispatch();
  const router = useRouter();

  const { gameIndex } = useSelector(({ game }) => game) ?? {};
  const { games, categories } = gameIndex ?? {};

  const { call } = useApi();
  const [params, setParams] = useState();

  const query = { page: 1, limit: 50 };

  useEffect(() => {
    if (!params || isEmpty(params)) return;

    Promise.all([
      call(
        getCategoryById(dispatch, params?.categoryId),
        call(getAllGame(dispatch, query)),
        call(getAllCategories(dispatch, query))
      ),
    ]);
  }, [params]);

  useEffect(() => {
    setParams(router.query);
  }, [router]);

  return (
    <>
      <Head>
        <title>Game detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className="w-min">
          <GameCategoryDetailGrid />
          <div className="grid-responsive grid gap-4 mt-[94px]">
            {games?.map((e, i) => (
              <GameItem
                key={e?.id}
                id={e?.id}
                index={i}
                thumbnail={e?.thumbnail}
                style={{ gridArea: "auto" }}
                title={e?.title}
              ></GameItem>
            ))}
          </div>
          <GameCategoryGrid categories={categories} />
        </div>
      </MainLayout>
    </>
  );
};

export default CategoryDetail;
