import GameCategoryDetailGrid from "@/components/ui/GameCategoryDetailGrid";
import { useApi } from "@/hooks/useApi";
import MainLayout from "@/layouts/MainLayout";
import { getCategoryById } from "@/services/game.service";
import { isEmpty } from "lodash";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

const CategoryDetail = () => {
  const dispatch = useDispatch();
  const router = useRouter();

  const { call } = useApi();
  const [params, setParams] = useState();

  useEffect(() => {
    if (!params || isEmpty(params)) return;

    Promise.all([call(getCategoryById(dispatch, params?.categoryId))]);
  }, [params]);

  useEffect(() => {
    setParams(router.query);
  }, [router]);

  return (
    <>
      <Head>
        <title>Game detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className="w-min">
          <GameCategoryDetailGrid />
        </div>
      </MainLayout>
    </>
  );
};

export default CategoryDetail;
