/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useState } from "react";

import Head from "next/head";

import MainLayout from "@/layouts/MainLayout";

import { useToast } from "@chakra-ui/react";

import { useDispatch } from "react-redux";

import { getHallOfFameByUsername } from "@/services/user.service";

import { notifyErrorMessage } from "@/utils/helper";

import HallOfFame from "@/components/other/HallOfFame";
import { useAuthContext } from "@/context/auth-context";

const MyHallOfFamePage = () => {
  const toast = useToast();
  const dispatch = useDispatch();

  const { userInfo } = useAuthContext();

  const handleGetHallOfFame = async () => {
    try {
      getHallOfFameByUsername(dispatch, userInfo?.username);
    } catch (error) {
      notifyErrorMessage(toast, error);
    }
  };

  useEffect(() => {
    if (!userInfo) return;
    handleGetHallOfFame();
  }, [userInfo]);

  // if (!isValidPage) return <PageNotFound />;
  return (
    <>
      <Head>
        <title>My Hall Of Fame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        {/* content  */}
        <HallOfFame></HallOfFame>
      </MainLayout>
    </>
  );
};

export default MyHallOfFamePage;
