/* eslint-disable react/no-unescaped-entities */
/* eslint-disable no-console */
import React from "react";

import Head from "next/head";
import MainLayout from "@/layouts/MainLayout";

const About = () => {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <main className="main static-page">
          <h1 className="static-page__ttl">ABOUT US</h1>
          <p className="static-page__txt">
            Welcome to Zeraverse.io! We are passionate about bringing you the
            best gaming experience possible, and we do that by offering a unique
            synchronous experience across games & devices.
          </p>
          <p className="static-page__txt">
            Our vision is to create a platform where players can enjoy their
            favorite games & earn rewards seamlessly across multiple games &
            devices, without ever missing a beat. Whether you're playing on your
            desktop, tablet, or mobile phone, our rewards system are designed to
            work flawlessly and synchronously, so you can play a game and bring
            the coin earned to other games, no matter which game you play.
          </p>
          <p className="static-page__txt">
            We believe that gaming should be an immersive, social experience,
            and that's why we've built our portal to be more than just a
            collection of games. Our community features allow you to chat in a
            group with other players, share your achievements, and showing your
            results in a Hall of Fame. We're constantly innovating and adding
            new features to make your gaming experience even more enjoyable.
          </p>
          <p className="static-page__txt">
            At our core, we're gamers just like you, and we're committed to
            bringing you the best possible gaming experience. So come join us,
            and let's game together!
          </p>
        </main>
      </MainLayout>
    </>
  );
};

export default About;
