/* eslint-disable @next/next/no-img-element */
import React from "react";

import Head from "next/head";

import MainLayout from "@/layouts/MainLayout";

import {
  IconCoin,
  IconEarn,
  IconGamePad,
  IconLeftWing,
  IconRightWing,
} from "@/resources/icons";

const AVATAR_URL =
  "https://img.freepik.com/premium-vector/cute-shiba-inu-dog-sitting-cartoon_138676-2436.jpg?w=2000";
const GAME_URL =
  "https://cdn.akamai.steamstatic.com/steam/apps/1817070/ss_dfba6f2477bfa42be69ddfdffbd421d3943d20bf.1920x1080.jpg?t=1673999865";

const HallOfFame = () => {
  const items = [
    {
      id: 1,
      icon: <IconEarn className="max-h-[128px] mb-2.5 mx-auto" />,
      value: 10000,
      title: "Earned Zera",
      desc: "",
    },
    {
      id: 2,
      icon: <IconGamePad className="max-h-[128px] mx-auto" />,
      value: 100,
      title: "Total games played",
      desc: "",
    },
    {
      id: 1,
      icon: (
        <div className="flex justify-between w-full pt-4 relative">
          <IconLeftWing />
          <span className="text-gradient-hof text-[90px] font-bold absolute left-[50%] translate-x-[-50%]">
            21
          </span>
          <IconRightWing />
        </div>
      ),
      value: null,
      title: "Highest Playstreak",
      desc: "Playstreak: 2 days",
    },
  ];

  const top_played_items = [
    {
      id: 1,
      imageUrl: GAME_URL,
      title: "Onmyoji The World",
      earnValue: 1000,
    },
    {
      id: 2,
      imageUrl: GAME_URL,
      title: "Marvel Fight",
      earnValue: 900,
    },
    {
      id: 1,
      imageUrl: GAME_URL,
      title: "Assasins Creed",
      earnValue: 900,
    },
    {
      id: 1,
      imageUrl: GAME_URL,
      title: "Raid",
      earnValue: 10,
    },
  ];

  return (
    <>
      <Head>
        <title>Hall Of Fame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        {/* content  */}
        <div className="">
          <div className="text-white bg-blur-800 border-[5px] border-violet-400 p-[62px] pt-2.5 rounded-[20px]">
            {/* title */}
            <div className="bg-pink-800 rounded-[20px] mx-auto py-2.5 text-[40px] text-center font-bold w-[280px] mb-[58px]">
              Hall Of Fame
            </div>

            {/* content */}
            <div className="p-16 border-[5px] border-pink-500 bg-[#5b21b666] rounded-[30px]">
              <div className="flex gap-20">
                {/* avatar */}
                <div className="max-w-[204px]">
                  <img
                    src={AVATAR_URL}
                    alt="avatar"
                    className="w-[204px] h-[204px] object-cover rounded-[20px]"
                  />
                  <h2 className="text-center font-bold text-base">User Name</h2>
                  <p className="text-[12px]">
                    Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et
                    massa mi.
                  </p>
                </div>

                {/* item */}
                <div className="grid grid-cols-1 min-[1250px]:grid-cols-2 min-[1492px]:grid-cols-3 gap-[25px]">
                  {items?.map(({ icon, value, desc, title }, i) => (
                    <div
                      key={i}
                      className="hall-of-fame__item min-w-[204px] min-h-[312px] border border-[#F9A8D4] rounded-[30px] pt-8 pb-2 px-2.5 text-center
                                 flex flex-col items-center justify-between"
                    >
                      <div className="w-full mb-[61px]">
                        {icon}
                        <h2 className="text-gradient-hof text-[28px] font-semibold">
                          {value}
                        </h2>
                      </div>
                      <div>
                        <h3 className="text-base font-bold">{title}</h3>
                        <p className="text-[10px] min-h-[15px]">{desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex justify-end">
                {/* top played */}
                <div className="max-w-[845px] w-full text-center">
                  <h1 className="text-[28px] font-semibold py-4">
                    Top game played
                  </h1>
                  <div className="w-full grid grid-cols-1 min-[1492px]:grid-cols-2 gap-x-5 gap-y-[15px]">
                    {top_played_items?.map(
                      ({ imageUrl, title, earnValue }, i) => (
                        <div
                          key={i}
                          className="bg-gradient-tgp w-full rounded-[20px] p-[10px] text-base font-bold
                        flex items-center justify-between"
                        >
                          <div className="flex items-center gap-2.5">
                            <img
                              src={imageUrl}
                              alt=""
                              className="w-[94px] h-[94px] object-cover rounded-2xl"
                            />
                            <p>{title}</p>
                          </div>
                          <div className="flex items-center gap-4">
                            <span>{earnValue}</span>
                            <IconCoin />
                          </div>
                        </div>
                      )
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </MainLayout>
      ;
    </>
  );
};

export default HallOfFame;
