import Head from "next/head";

import Games from "@/api/games.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="game-grid">
        {Array(150)
          .fill(0)
          .map((e, i) => (
            <div
              key={i}
              className="bg-blue-400 w-[94px] h-[94px] rounded-2xl"
            ></div>
          ))}
        {Games.map((e, i) => (
          <div
            key={i}
            className={`bg-blue-500 game-size-${e?.size} rounded-2xl`}
            style={{
              gridArea: `ip${e?.ip} / ip${e?.ip} / ip${e?.ip} / ip${e?.ip}`,
            }}
          ></div>
        ))}
      </div>
    </>
  );
}
