/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";

import Head from "next/head";

import MainLayout from "@/layouts/MainLayout";

import GameGrid from "@/components/ui/GameGrid";
import GameCategoryGrid from "@/components/ui/GameCategoryGrid";

import { getAllCategories, getAllGame } from "@/services/game.service";

import { useApi } from "@/hooks/useApi";

export default function Home() {
  const dispatch = useDispatch();

  const { call } = useApi();

  const { gameIndex } = useSelector(({ game }) => game) ?? {};
  const { games, categories } = gameIndex ?? {};

  // const params = { page: 1, limit: 50 };

  useEffect(() => {
    Promise.all([call(getAllGame(dispatch)), call(getAllCategories(dispatch))]);
  }, []);

  return (
    <>
      <Head>
        <title>Zera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className="w-responsive">
          <GameGrid games={games} />
          <GameCategoryGrid categories={categories} />
        </div>
      </MainLayout>
    </>
  );
}
