/* eslint-disable react/no-unescaped-entities */
/* eslint-disable no-console */
import React from "react";

import Head from "next/head";
import MainLayout from "@/layouts/MainLayout";
import SidebarMB from "@/components/responsive/SidebarMB";
import PreviousRouter from "@/components/previousRouter/PreviousRouter";

const Policy = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className="max-[990px]:flex flex-col">
          <SidebarMB
            className={"tbl-flex"}
            childClassName={"static-important mb-5"}
          />
          <main className="main static-page">
            <PreviousRouter />

            <h1 className="static-page__ttl">PRIVACY POLICY</h1>

            <h2 className="static-page__ttl-roman">
              I. WHICH DATA DO WE COLLECT?
            </h2>
            <h3 className="static-page__ttl-number">
              1. Data we receive from you
            </h3>
            <p className="static-page__txt">
              Only when you in the contact form provided on our Site, subscribe
              to our newsletter, or send us an e-mail, we will optionally
              process the following types of personal data based on consent:
              <br></br>· First name
              <br></br>· Name
              <br></br>· E-mail
              <br></br>· Other information that you provide.
              <br></br>If you register an account with us, you give explicit
              consent to collect a password, email address, phone number, user
              agent, and IP address. We do not store this data ourselves. The
              data is used to enable end-user authentication and facilitate
              end-user account management. It also uses user-agent strings and
              IP addresses to provide added security and prevent abuse during
              sign-up and authentication.
              <br></br>IP addresses are logged for a few weeks. Other
              authentication information is retained until you initiate deletion
              of the associated user, after which data is removed from live and
              backup systems within 180 days. To opt out of our account service
              and/or delete a user, please email info@zeraverse.io.
            </p>
            <h3 className="static-page__ttl-number">
              2. Data we receive automatically
            </h3>
            <p className="static-page__txt">
              We can collect some personal data with cookies: see Section V of
              this Privacy Policy.
              <br></br>Some other (personal) data may be collected without the
              use of cookies. Said data can only be read and used during your
              visit to our Site:
              <br></br>· Your IP-address (used e.g. for preventing double voting
              and location based advertising);
              <br></br>· Your browser type and revision;
              <br></br>· The last visited internet page;
              <br></br>· (mobile) device ID's;
              <br></br>· cookie data;
              <br></br>User level data (i.e. whether a user viewed or clicked on
              an advertisement);
            </p>
            <h3 className="static-page__ttl-number">
              3. Data we receive from third parties
            </h3>
            <p className="static-page__txt">
              When we receive Personal Information from third parties, we will
              inform you personally.
            </p>

            <h2 className="static-page__ttl-roman">
              II. WHY DO WE COLLECT THESE DATA? BASED ON WHICH LEGAL GROUND?
            </h2>
            <p className="static-page__txt">
              Your personal data will be used to enable us to optimize the
              services we render and the content we provide on the Site. In
              certain cases when we are under a legal requirement to process
              personal data, like age limits, we will process said personal
              data.
              <br></br>We may also use your personal data for direct marketing
              purposes, such as updates on new or existing games and
              newsletters.
              <br></br>We may opt to use your personal data for statistical
              purposes and to improve our services and product. These processing
              activities are thus based on a justified legitimate interest of
              Zeraverse.io.
              <br></br> Advertisers on our website might use information
              gathered by the use cookies and/or web beacons for the purpose of
              online behavioral advertising and/or multisite advertising.
              Further information as regards the use of cookies and web beacons
              is set out in Section V below.
              <br></br>Zeraverse.io is not responsible for any personal data
              collected via any third-party software or methods present on the
              Site and to which said third parties' general terms and conditions
              may apply.
              <br></br>You are advised not to use your real name or real e-mail
              address in any of the games provided on our Site including,
              without limitation, when engaging in multi-play.
            </p>

            <h2 className="static-page__ttl-roman">
              III. DATA RETENTION PERIODS
            </h2>
            <p className="static-page__txt">
              Your personal data will only be processed for as long as this is
              necessary for the purposes mentioned above. Unless there is a
              justified reason to retain the personal data, for example within
              the framework of customer relation management, your personal data
              will be deleted one month after you failed to visit our site
              during a consecutive period of [2] years.
            </p>

            <h2 className="static-page__ttl-roman">IV. YOUR RIGHTS</h2>
            <p className="static-page__txt">
              You can get access to your personal data and rectify or erase
              them, free of charge. You also have the right to restrict the
              processing of your personal data.
              <br></br>If you do not wish to receive newsletters or information
              about our products or services, you can at any moment and without
              any need for justification, object to the processing of your
              personal data for these purposes (“unsubscribe”). You can do this
              by sending us an e-mail or by contacting as at the address
              mentioned below. You can also do this by clicking on the
              unsubscribe link in our advertising e-mails.
              <br></br>Moreover, you have the right to data portability for the
              personal data you have provided to Zeraverse.io if any and to the
              extent that Zeraverse.io has retained your personal data.
              <br></br>To exercise these rights, we ask you to send a clear
              request, to the address mentioned below, that states clearly what
              it is you want to know, rectify, or erase. This request needs to
              be signed and dated and contain a copy of the front side of your
              identity card or driver's license.
              <br></br>You should specifically motivate your request if you want
              to rectify or erase personal data or restrict the processing
              thereof. Once these conditions are fulfilled, Zeraverse.io will
              execute your request as soon as possible and send you a message on
              this matter.
            </p>

            <h2 className="static-page__ttl-roman">V. COOKIES</h2>
            <p className="static-page__txt">
              What are cookies?
              <br></br>Cookies are small files that are saved on your computer
              when you visit web pages. They contain information linked to a web
              browser and the specific website. They are saved in a specific
              folder on your hard drive. If you return to a specific website,
              this page can recognize the visitor by means of the cookie and
              further elaborate the history. A web beacon is an (often
              transparent) graphic image, usually no larger than 1 pixel, that
              is placed on a website and that is used to monitor the behavior of
              the user visiting the website.
              <br></br>Cookies are used to increase visitor-friendliness: by
              identifying visitors with a cookie, they do not always have to
              enter the same data such as login information or screen settings
              every time you visit the website.
              <br></br>Which kind of cookies exist?
              <br></br>Often a distinction is made between two large groups of
              cookies:
              <br></br> First party cookies: these cookies are created by a
              website to have the web page function better. They regulate the
              technical part of a site, such as language choice or remembering
              the products in the shopping basket in an online store. The
              visited website creates and places first party cookies.
              <br></br>Third party cookies: these cookies are created and placed
              on your computer by another (third) party than the website you
              visit. They remember the behavior of a surfer. Examples are social
              media such as Facebook or Twitter, but Google Analytics as well.
              This is the system used most to measure website visits.
              <br></br>Cookies required for the correct functioning of the Site
              do not require permission. All other cookies do.
              <br></br>Which cookies do we use?
              <br></br>We will only use first party cookies to help improve your
              user experience on the Site. We would do this by recording
              specific information about the user such as the language chosen,
              the pages visited and the duration of the visits.
              <br></br>We may offer games from third-party game distributors on
              our portal. By playing a third-party game, your Personal Data may
              be processed by the third-party game distributor (directly or
              through the use of cookies or similar technology). Please note
              that if you choose to play a third-party game, you are playing
              that game in the environment of that game's third-party developer,
              over which we have no control.
              <br></br>Your acceptance of this Privacy Policy by using the Site,
              entails that third parties may drop cookies and/or use web beacons
              for advertising and tracking purposes.
              <br></br>Third parties might use information gathered by cookies
              and/or web beacons for the purpose of online behavioral
              advertising and/or multisite advertising. The types of information
              that is gathered by third party cookies and/or web beacons as well
              as the purpose(s) for which this information is used, are set out
              in the privacy policy of said third parties which Zeraverse.io
              encourages you to review. Zeraverse.io declines all and any
              liability for any third-party cookies or web beacons deployed by
              third parties for whatever purpose.
              <br></br>In addition, the Site also uses third party cookies such
              as cookies from Google Analytics.
              <br></br>Google Analytics is a free service by Google to collect
              statistics of websites and to represent them in detail. The
              website administrator thus has a clear view on visitor flows,
              traffic flows and page displays. This way it is possible to adapt
              parts of a website or complete websites to the behavior and
              interests of the visitors.
              <br></br>How to manage cookies?
              <br></br>You can do so by adapting your browser settings. You can
              choose to block cookies or to accept only cookies from specific
              websites.
              <br></br>Below, you will find an overview of the possibilities the
              browsers offer to manage cookies.
              <br></br>Google Chrome: Open your browser. Click the Chrome menu
              and choose settings. Click display advanced settings and then the
              button Settings for content in the 'Privacy' section. In the
              'Cookies' section you can edit your cookies settings and remove
              cookies.
              <br></br>Internet Explorer: Open your browser. Click Tools and
              then Internet options. Click the 'Privacy' section and choose the
              level you want with the slide control. You can also change this
              manually by clicking Advanced. A distinction is made between
              permanent direct cookies (first party cookies), permanent indirect
              cookies (third party cookies) and temporary cookies (session
              cookies). You can remove cookies by means of the main screen of
              internet options.
              <br></br>Mozilla Firefox: Open your browser. Select Privacy. Set
              Firefox to Use adapted settings for history. To switch cookies on,
              put a checkmark with Accept cookies of websites. To switch off
              cookies, remove this checkmark. Firefox also gives you the
              possibility to switch off cookies of third parties (third party
              cookies). Furthermore you can set for how long cookies can be
              kept. Click Show cookies and you can remove one or several
              cookies.
              <br></br>Safari: Open your browser. In Safari, cookie
              administration is limited to one screen. In tab sheet Preferences
              click Privacy. You then have three possibilities to accept
              cookies. Via Show Cookies you can also remove cookies.
              <br></br>Opera: Open your browser. Click the Extra menu and then
              Preferences. Via Advanced and Cookies you can set your cookies
              settings. You also have the possibility to have new cookies
              removed automatically when you close each Internet session.
              Moreover, you can decide about each cookie that is sent to your
              computer. You do this by clicking Ask me before accepting cookies.
              Each time a site wants to save a cookie, a dialog box is
              displayed.
            </p>

            <h2 className="static-page__ttl-roman">VI. SECURITY MEASURES</h2>
            <p className="static-page__txt">
              Zeraverse.io has taken all reasonable and appropriate technical
              and organizational measures to ensure that your Personal
              Information is processed securely.
              <br></br> If you have any questions on these security measures,
              feel free to contact us at the address mentioned below.
              <br></br>Within Zeraverse.io, personal data is only available to
              people who need to have access to it in relation to their job.
              <br></br> At no moment in time will we directly sell or rent out
              your personal data to third parties. Occasionally we may use an
              external processor. If we do this, we will always ensure that your
              information is handled confidentially and in a safe manner. We
              also always draw up a contract with these processors. This way the
              processor will never be allowed to use your data on its own
              initiative and your data has to be erased as soon as the processor
              has finished the assignment.
            </p>

            <h2 className="static-page__ttl-roman">
              VII. CONTACT INFORMATION OF DATA CONTROLLER
            </h2>
            <p className="static-page__txt">
              For all your questions or complaints regarding this Privacy
              Policy, you should contact us at the following e-mail address:
              info@zeraverse.io or through our contact form.
            </p>
          </main>
        </div>
      </MainLayout>
    </>
  );
};

export default Policy;
