import MainLayout from "@/layouts/MainLayout";
import React, { useState } from "react";

import Head from "next/head";
import TopBar from "@/components/ui/TopBar";
import AvatarItem from "@/components/shop/AvatarItem";
import { Checkbox } from "@chakra-ui/react";
import { SIMPLE_SHOP_TAB } from "@/utils/constant";
import CoverPageItem from "@/components/shop/CoverPageItem";
import PlayTimeItem from "@/components/shop/PlayTimeItem";

const tabs = [
  {
    title: "Avatar",
    tabName: SIMPLE_SHOP_TAB.AVATAR,
  },
  {
    title: "Cover page",
    tabName: SIMPLE_SHOP_TAB.COVER_PAGE,
  },
  {
    title: "Playtimes",
    tabName: SIMPLE_SHOP_TAB.PLAYTIMES,
  },
];

const SimpleShop = () => {
  const [tab, setTab] = useState(SIMPLE_SHOP_TAB.AVATAR);

  return (
    <>
      <Head>
        <title>Simple Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        {/* content  */}
        <div className="">
          <div className="text-white bg-blur-800 border-[5px] border-violet-400 p-[62px] pt-2.5 rounded-[20px]">
            {/* title */}
            <div className="bg-pink-800 rounded-[20px] mx-auto py-2.5 text-[40px] text-center font-bold w-[280px] mb-[58px]">
              Simple Shop
            </div>

            {/* tab */}
            <div className="flex gap-3 justify-center">
              {tabs?.map(({ title, tabName }, i) => (
                <div
                  key={i}
                  onClick={() => setTab(tabName)}
                  className={`${
                    tabName === tab
                      ? "bg-pink-800 text-white border border-pink-500"
                      : "bg-violet-900 text-[#ffffffb3] border border-violet-500"
                  } text-center text-base font-bold rounded-t-[20px] w-[120px]  border-b-0 py-2.5 cursor-pointer`}
                >
                  {title}
                </div>
              ))}
            </div>

            {/* content */}
            <div className="pt-[18px] px-[54px] pb-[26px] border-[5px] border-pink-500 bg-[#5b21b666] rounded-[30px]">
              {/* checkbox */}
              <div className="flex gap-4 justify-end mb-[26px]">
                <Checkbox colorScheme="pink" defaultChecked>
                  All
                </Checkbox>
                <Checkbox colorScheme="pink" defaultChecked>
                  Buy
                </Checkbox>
                <Checkbox colorScheme="pink" defaultChecked>
                  Owned
                </Checkbox>
              </div>
              {/* list item  */}

              {tab === SIMPLE_SHOP_TAB.AVATAR ? (
                <div
                  className="grid grid-cols-1 justify-center
                  min-[990px]:grid-cols-2 min-[1248px]:grid-cols-3 min-[1540px]:grid-cols-4 gap-4"
                >
                  {Array(8)
                    .fill(0)
                    .map((e, i) => (
                      <AvatarItem key={i} />
                    ))}
                </div>
              ) : tab === SIMPLE_SHOP_TAB.COVER_PAGE ? (
                <div className="grid grid-cols-2 gap-4">
                  {Array(4)
                    .fill(0)
                    .map((e, i) => (
                      <CoverPageItem key={i} />
                    ))}
                </div>
              ) : tab === SIMPLE_SHOP_TAB.PLAYTIMES ? (
                <div
                  className="grid grid-cols-1 justify-center
                  min-[990px]:grid-cols-2 min-[1248px]:grid-cols-3 min-[1540px]:grid-cols-4 gap-4"
                >
                  {Array(8)
                    .fill(0)
                    .map((e, i) => (
                      <PlayTimeItem key={i} />
                    ))}
                </div>
              ) : null}
            </div>
          </div>
        </div>
      </MainLayout>
      ;
    </>
  );
};

export default SimpleShop;
