import React from "react";

import Head from "next/head";
import MainLayout from "@/layouts/MainLayout";

import GameDetailGrid from "@/components/ui/GameDetailGrid";
import GameCategoryGrid from "@/components/ui/GameCategoryGrid";

const GameDetail = () => {
  return (
    <>
      <Head>
        <title>Game detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className="w-min">
          <GameDetailGrid />
          <GameCategoryGrid />
        </div>
      </MainLayout>
    </>
  );
};

export default GameDetail;

// export async function getStaticProps(context) {
//   const response = await fetch("https://jsonplaceholder.typicode.com/posts");
//   const data = await response.json();

//   return {
//     props: {
//       posts: data,
//     },
//   };
// }

// export async function getStaticPaths() {
//   return {
//     paths: [],
//     fallback: true, // can also be true or 'blocking'
//   };
// }
